# Generated by Django 5.1.6 on 2025-03-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='label',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
